version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: infra_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: infra_admin
      POSTGRES_PASSWORD: infra_pass
      POSTGRES_DB: university_dashboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: infra_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
